//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Cisst
{
    [Serializable]
    public class DoubleVecMsg : Message
    {
        public const string k_RosMessageName = "cisst_msgs/DoubleVec";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double[] data;

        public DoubleVecMsg()
        {
            this.header = new Std.HeaderMsg();
            this.data = new double[0];
        }

        public DoubleVecMsg(Std.HeaderMsg header, double[] data)
        {
            this.header = header;
            this.data = data;
        }

        public static DoubleVecMsg Deserialize(MessageDeserializer deserializer) => new DoubleVecMsg(deserializer);

        private DoubleVecMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "DoubleVecMsg: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
