//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Cisst
{
    [Serializable]
    public class ConvertFloat64ArrayRequest : Message
    {
        public const string k_RosMessageName = "cisst_msgs/ConvertFloat64Array";
        public override string RosMessageName => k_RosMessageName;

        public double[] input;

        public ConvertFloat64ArrayRequest()
        {
            this.input = new double[0];
        }

        public ConvertFloat64ArrayRequest(double[] input)
        {
            this.input = input;
        }

        public static ConvertFloat64ArrayRequest Deserialize(MessageDeserializer deserializer) => new ConvertFloat64ArrayRequest(deserializer);

        private ConvertFloat64ArrayRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.input, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.input);
            serializer.Write(this.input);
        }

        public override string ToString()
        {
            return "ConvertFloat64ArrayRequest: " +
            "\ninput: " + System.String.Join(", ", input.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
