//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Crtk
{
    [Serializable]
    public class QueryForwardKinematicsRequest : Message
    {
        public const string k_RosMessageName = "crtk_msgs/QueryForwardKinematics";
        public override string RosMessageName => k_RosMessageName;

        public double[] jp;
        public Geometry.PoseMsg cp;

        public QueryForwardKinematicsRequest()
        {
            this.jp = new double[0];
            this.cp = new Geometry.PoseMsg();
        }

        public QueryForwardKinematicsRequest(double[] jp, Geometry.PoseMsg cp)
        {
            this.jp = jp;
            this.cp = cp;
        }

        public static QueryForwardKinematicsRequest Deserialize(MessageDeserializer deserializer) => new QueryForwardKinematicsRequest(deserializer);

        private QueryForwardKinematicsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.jp, sizeof(double), deserializer.ReadLength());
            this.cp = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.jp);
            serializer.Write(this.jp);
            serializer.Write(this.cp);
        }

        public override string ToString()
        {
            return "QueryForwardKinematicsRequest: " +
            "\njp: " + System.String.Join(", ", jp.ToList()) +
            "\ncp: " + cp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
