//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Crtk
{
    [Serializable]
    public class QueryForwardKinematicsResponse : Message
    {
        public const string k_RosMessageName = "crtk_msgs/QueryForwardKinematics";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg cp;
        public bool result;
        public string message;

        public QueryForwardKinematicsResponse()
        {
            this.cp = new Geometry.PoseMsg();
            this.result = false;
            this.message = "";
        }

        public QueryForwardKinematicsResponse(Geometry.PoseMsg cp, bool result, string message)
        {
            this.cp = cp;
            this.result = result;
            this.message = message;
        }

        public static QueryForwardKinematicsResponse Deserialize(MessageDeserializer deserializer) => new QueryForwardKinematicsResponse(deserializer);

        private QueryForwardKinematicsResponse(MessageDeserializer deserializer)
        {
            this.cp = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.result);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cp);
            serializer.Write(this.result);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "QueryForwardKinematicsResponse: " +
            "\ncp: " + cp.ToString() +
            "\nresult: " + result.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
