//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Crtk
{
    [Serializable]
    public class QueryInverseKinematicsResponse : Message
    {
        public const string k_RosMessageName = "crtk_msgs/QueryInverseKinematics";
        public override string RosMessageName => k_RosMessageName;

        public double[] jp;
        public bool result;
        public string message;

        public QueryInverseKinematicsResponse()
        {
            this.jp = new double[0];
            this.result = false;
            this.message = "";
        }

        public QueryInverseKinematicsResponse(double[] jp, bool result, string message)
        {
            this.jp = jp;
            this.result = result;
            this.message = message;
        }

        public static QueryInverseKinematicsResponse Deserialize(MessageDeserializer deserializer) => new QueryInverseKinematicsResponse(deserializer);

        private QueryInverseKinematicsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.jp, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.result);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.jp);
            serializer.Write(this.jp);
            serializer.Write(this.result);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "QueryInverseKinematicsResponse: " +
            "\njp: " + System.String.Join(", ", jp.ToList()) +
            "\nresult: " + result.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
