//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Crtk
{
    [Serializable]
    public class QueryInverseKinematicsRequest : Message
    {
        public const string k_RosMessageName = "crtk_msgs/QueryInverseKinematics";
        public override string RosMessageName => k_RosMessageName;

        //  request needs
        //  - cp: cartesian pose
        //  - jp: reference joint position
        public Geometry.PoseMsg cp;
        public double[] jp;

        public QueryInverseKinematicsRequest()
        {
            this.cp = new Geometry.PoseMsg();
            this.jp = new double[0];
        }

        public QueryInverseKinematicsRequest(Geometry.PoseMsg cp, double[] jp)
        {
            this.cp = cp;
            this.jp = jp;
        }

        public static QueryInverseKinematicsRequest Deserialize(MessageDeserializer deserializer) => new QueryInverseKinematicsRequest(deserializer);

        private QueryInverseKinematicsRequest(MessageDeserializer deserializer)
        {
            this.cp = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.jp, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cp);
            serializer.WriteLength(this.jp);
            serializer.Write(this.jp);
        }

        public override string ToString()
        {
            return "QueryInverseKinematicsRequest: " +
            "\ncp: " + cp.ToString() +
            "\njp: " + System.String.Join(", ", jp.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
