//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Crtk
{
    [Serializable]
    public class TriggerOperatingStateResponse : Message
    {
        public const string k_RosMessageName = "crtk_msgs/TriggerOperatingState";
        public override string RosMessageName => k_RosMessageName;

        public OperatingStateMsg operating_state;

        public TriggerOperatingStateResponse()
        {
            this.operating_state = new OperatingStateMsg();
        }

        public TriggerOperatingStateResponse(OperatingStateMsg operating_state)
        {
            this.operating_state = operating_state;
        }

        public static TriggerOperatingStateResponse Deserialize(MessageDeserializer deserializer) => new TriggerOperatingStateResponse(deserializer);

        private TriggerOperatingStateResponse(MessageDeserializer deserializer)
        {
            this.operating_state = OperatingStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.operating_state);
        }

        public override string ToString()
        {
            return "TriggerOperatingStateResponse: " +
            "\noperating_state: " + operating_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
