//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Crtk
{
    [Serializable]
    public class TriggerOperatingStateRequest : Message
    {
        public const string k_RosMessageName = "crtk_msgs/TriggerOperatingState";
        public override string RosMessageName => k_RosMessageName;


        public TriggerOperatingStateRequest()
        {
        }
        public static TriggerOperatingStateRequest Deserialize(MessageDeserializer deserializer) => new TriggerOperatingStateRequest(deserializer);

        private TriggerOperatingStateRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "TriggerOperatingStateRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
